version: '3.8'

services:
  # 1. Сервер базы данных
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db-container
    environment:
      POSTGRES_DB: project_dima_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    networks:
      - dima-network
    restart: unless-stopped

  # 2. Ваше Java-приложение
  java-app:
    build: .
    container_name: java-app-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/project_dima_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    networks:
      - dima-network
    depends_on:
      - postgres-db
    restart: unless-stopped

  # 3. Сборщик метрик Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - dima-network
    restart: unless-stopped

  # 4. Grafana (Рисует дашборды)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - dima-network
    restart: unless-stopped

  # 5. Loki (Хранит логи)
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - dima-network
    restart: unless-stopped

  # 6. Grafana Alloy (Собирает логи из Docker)
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    networks:
      - dima-network
    depends_on:
      - loki
    restart: unless-stopped

networks:
  dima-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-storage:
  loki-data: