spring.application.name=ProjectDima3

# ??????????? ? PostgreSQL (?? ?????? ??????? ?? project_dima_db ? pgAdmin!)
spring.datasource.url=jdbc:postgresql://localhost:5432/project_dima_db
spring.datasource.username=postgres
spring.datasource.password=????_??????

# ????????? JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml